### ISSUE TITLE
Components: Log-In Form

### ISSUE THREAD

**Issue by epuermas** [paocastrob/FinalProject#9]
- [x] Log-In Form
The log-in form will ask for the user's e-mail and password.  It will have a "remember me" check-box, and it will have a button that says "Log-In".

**Comment by Frrimix** [comment]
Forgot your password link was added to the Log-In Form

**Comment by epuermas** [comment]
> Forgot your password link was added to the Log-In Form

@Frrimix forgot password link as added to the Log-In Form
